const URL_BASE = 'http://127.0.0.1:8000';
export const API_ADMIN_BOOKS = URL_BASE + '/api/admin/books';
export const API_ADMIN_BOOK = URL_BASE + '/api/admin/book/detail/';
export const API_ADMIN_BOOK_ADD = URL_BASE + '/api/admin/book/add';
export const API_ADMIN_BOOK_UPDATE = URL_BASE + '/api/admin/book/update';
export const API_ADMIN_BOOK_DELETE = URL_BASE + '/api/admin/book/delete/';
export const API_ADMIN_ORDERS = URL_BASE + '/api/admin/orders';
export const API_ADMIN_GET_ORDER = URL_BASE + '/api/admin/order/';
export const API_ADMIN_DELETE_ORDER = URL_BASE + '/api/admin/order/';
